set_property MARK_DEBUG false [get_nets clk100M_IBUF]
set_property MARK_DEBUG false [get_nets TOP_TRANS/clk]
set_property MARK_DEBUG false [get_nets TOP_TRANS/stable_send]

set_property MARK_DEBUG true [get_nets send_IBUF]
set_property MARK_DEBUG true [get_nets TOP_TRANS/clk_UART]
set_property MARK_DEBUG true [get_nets TOP_TRANS/button_out]
set_property MARK_DEBUG true [get_nets Tx_OBUF]
set_property MARK_DEBUG true [get_nets {TOP_TRANS/count[0]}]
set_property MARK_DEBUG true [get_nets {TOP_TRANS/count[1]}]
set_property MARK_DEBUG true [get_nets {TOP_TRANS/count[2]}]
set_property MARK_DEBUG true [get_nets {TOP_TRANS/count[3]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {TOP_TRANS/count[0]} {TOP_TRANS/count[1]} {TOP_TRANS/count[2]} {TOP_TRANS/count[3]}]]

set_property MARK_DEBUG true [get_nets {switches_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[6]}]
set_property MARK_DEBUG true [get_nets {switches_IBUF[7]}]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data7]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data6]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data5]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data4]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data3]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data2]
set_property MARK_DEBUG true [get_nets TOP_TRANS/OUTREG/data1]
set_property MARK_DEBUG true [get_nets {TOP_TRANS/OUTREG/out_reg_reg_n_0_[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk100M_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {TOP_TRANS/counter[0]} {TOP_TRANS/counter[1]} {TOP_TRANS/counter[2]} {TOP_TRANS/counter[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list TOP_TRANS/button_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list TOP_TRANS/clk_UART]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list TOP_TRANS/OUTREG/data1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list TOP_TRANS/OUTREG/data2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list TOP_TRANS/OUTREG/data3]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list TOP_TRANS/OUTREG/data4]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list TOP_TRANS/OUTREG/data5]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list TOP_TRANS/OUTREG/data6]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list TOP_TRANS/OUTREG/data7]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {TOP_TRANS/OUTREG/out_reg_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list send_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list TOP_TRANS/SM/state_i_1_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list Tx_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk100M_IBUF_BUFG]
